# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_context_postname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='postName',
            field=models.CharField(max_length=20),
        ),
    ]
