# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171103_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
