# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='postID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
