# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171107_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='postDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
