# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171107_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='postDescription',
            field=models.CharField(default=set, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='context',
            name='postImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
