# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171114_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='toDo',
        ),
        migrations.AddField(
            model_name='context',
            name='todo1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='todo2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='todo3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='todo4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='todo5',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
