# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_context_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='member1',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
