# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_context_member2'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='recentChangedBy',
            field=models.TextField(default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='context',
            name='recentChangedDescription',
            field=models.TextField(default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='context',
            name='recentChangedTitle',
            field=models.TextField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
