# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171205_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='projectDuration',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
